### ISSUE TITLE
README should have lifecycle badge to indicate status

### ISSUE THREAD

**Issue by joethorley** [flyaflya/causact#50]
In particular further down the README it states that

```
> NOTE: Package is under active development. Breaking changes are to be expected.  Feedback and encouragement is appreciated via github issues or Twitter (https://twitter.com/preposterior).
```

however this information should be immediately conveyed to users via a lifecycle badge at the top of the README.

See for example https://lifecycle.r-lib.org/articles/stages.html

https://github.com/openjournals/joss-reviews/issues/4415

**Comment by flyaflya** [comment]
Add a "maturing" badge to the readme as the package has been stable for over a year without breaking changes.  I also labelled each function with a badge to show that most of the functionality is anticipated to be stable.

Fixed in https://github.com/flyaflya/causact/commit/9320676955a8b74f8f9670f6cc154b6d73ac353f
